<a href="https://colab.research.google.com/github/OGSUPRA/proga/blob/master/datasince.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import os

df = pd.read_csv('/content/drive/MyDrive/data_set/data1.csv')
df

,Unnamed: 0,test_values,Unnamed: 2,for_notes,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,cashe,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,0,NaN,NaN,NaN,Resort Hotel,0.0,342.0,2015.0,July,NaN,...,No Deposit,NaN,NaN,0.0,Transient,0.0,0.0,0.0,Check-Out,2015-07-01
1,1,NaN,NaN,NaN,For notes:,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,NaN,NaN,NaN,Resort Hotel,0.0,7.0,2015.0,July,NaN,...,No Deposit,NaN,NaN,0.0,Transient,75.0,0.0,0.0,Check-Out,2015-07-02
3,3,NaN,NaN,NaN,For notes:,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,NaN,NaN,NaN,Resort Hotel,0.0,14.0,2015.0,July,NaN,...,No Deposit,240.0,NaN,0.0,Transient,98.0,0.0,1.0,Check-Out,2015-07-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23873,23873,NaN,NaN,NaN,For notes:,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23874,23874,NaN,NaN,NaN,Resort Hotel,0.0,16.0,2016.0,April,NaN,...,No Deposit,71.0,NaN,0.0,Transient,48.1,0.0,0.0,Check-Out,2016-05-06
23875,23875,NaN,NaN,NaN,For notes:,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23876,23876,NaN,NaN,NaN,Resort Hotel,0.0,1.0,2016.0,May,NaN,...,No Deposit,314.0,NaN,0.0,Transient,56.0,1.0,0.0,Check-Out,2016-05-06
23877,23877,NaN,NaN,NaN,For notes:,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN